# TTS CLI Configuration
# This file uses a flat structure for simplicity.
# Environment variable overrides: TTS_<KEY_NAME>=<value>

[network]
chatterbox_server_port = 12345
socket_recv_buffer_size = 4096
http_streaming_chunk_size = 1024

[timeouts]
server_startup_timeout = 30
server_poll_interval = 1
socket_connection_timeout = 1
voice_loading_timeout = 30
audio_check_timeout = 2
ffprobe_timeout = 5
ffmpeg_validation_timeout = 5
ffplay_timeout = 5
ffplay_termination_timeout = 2
ffmpeg_conversion_timeout = 30

[ui]
double_click_time = 0.8
filter_panel_width = 20
preview_panel_width = 18
status_display_time = 1000
click_feedback_time = 500
success_message_time = 1500
page_scroll_amount = 10
printable_char_range_start = 32
printable_char_range_end = 126

[audio]
audio_16bit_scale = 32767
audio_amplitude_limit = 0.95
audio_channels = 1
audio_sample_width = 2
audio_cards_min_size = 0

[elevenlabs]
default_stability = 0.5
default_similarity_boost = 0.5
default_style = 0.0
voice_id_length = 32
api_key_length = 32

[google]
default_speaking_rate = 1.0
default_pitch = 0.0
api_key_length = 39
oauth_token_min_length = 50
service_account_json_min_length = 100

[openai]
api_key_min_length = 40

[chatterbox]
default_exaggeration = 0.5
default_cfg_weight = 0.5
default_temperature = 0.8
default_min_p = 0.05

[http]
unauthorized = 401
forbidden = 403
rate_limit = 429
payment_errors = [402, 409]
server_error_range_start = 500
server_error_range_end = 600
error_message_max_length = 100

[streaming]
progress_interval = 10
playback_start_threshold = 3

[voices]
provider_sample_voices_count = 5
voice_list_max_display = 15
voice_name_display_length = 25
voice_name_truncation_offset = 18

[system]
thread_pool_max_workers = 1
memory_gb_conversion_factor = 1024