"""Test utilities package for TTS CLI tests."""

from .test_helpers import (
    AudioValidationResult,
    CLITestHelper,
    PROVIDER_SHORTCUTS_TEST_DATA,
    assert_provider_called_with,
    cli_helper,
    compare_audio_validation_results,
    config_factory,
    create_corrupted_audio_file,
    create_empty_audio_file,
    create_mock_api_response,
    create_mock_audio_file,
    create_mock_provider,
    create_realistic_audio_file,
    create_test_config,
    detect_silence,
    estimate_audio_duration_from_text,
    extract_audio_metadata,
    measure_synthesis_performance,
    mock_provider_factory,
    parametrize_provider_shortcuts,
    temp_audio_factory,
    validate_audio_file,
    validate_audio_file_comprehensive,
    validate_audio_format_compatibility,
    validate_test_environment,
)

__all__ = [
    "AudioValidationResult",
    "CLITestHelper",
    "PROVIDER_SHORTCUTS_TEST_DATA",
    "assert_provider_called_with",
    "cli_helper",
    "compare_audio_validation_results",
    "config_factory",
    "create_corrupted_audio_file",
    "create_empty_audio_file",
    "create_mock_api_response",
    "create_mock_audio_file",
    "create_mock_provider",
    "create_realistic_audio_file",
    "create_test_config",
    "detect_silence",
    "estimate_audio_duration_from_text",
    "extract_audio_metadata",
    "measure_synthesis_performance",
    "mock_provider_factory",
    "parametrize_provider_shortcuts",
    "temp_audio_factory",
    "validate_audio_file",
    "validate_audio_file_comprehensive",
    "validate_audio_format_compatibility",
    "validate_test_environment",
]